In [30]:
#Question 1

In [31]:
import numpy as np
t=list(map(int,input('input the list of the array: ').split(',')))
r=list(map(int,input('input the second list of the array: ').split(',')))
x=np.array([r,t])
print('your array:',x)
e=x.tolist()
print('your list:',e)

input your list:  1,2,3,4
input your list:  76,5,4,3


your array: [[76  5  4  3]
 [ 1  2  3  4]]
your list: [[76, 5, 4, 3], [1, 2, 3, 4]]


In [15]:
#Question 2

In [1]:
import numpy as np
m = np.arange(2,11).reshape(3,3)
print("Original array:")
print(m)
result =  np.trace(m)
print("The sum of the diagonal elements of the array=")
print(result)

Original array:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
The sum of the diagonal elements of the array=
18


In [49]:
#Question 3

In [67]:
import numpy as np
t=list(map(int,input('input the list of the array: ').split(',')))
r=list(map(int,input('input the second list of the array: ').split(',')))
e=np.array([r,t],dtype=object)
print("Your array is",e)
x=int(input('input the X:'))
for i in e:
    for j in i:
        if j>=x:
            print(j)
else:
    print("There is no number")


input the list of the array:  2,1
input the second list of the array:  1,2
input the X: 10


no number


In [55]:
#Question 3

In [68]:
import numpy as np
t=list(map(int,input('input the list of the first array: ').split(',')))
r=list(map(int,input('input the second list of the first array: ').split(',')))
A=np.array([t,r])
print('Your first array:',A)
t=list(map(int,input('input the list of the second array: ').split(',')))
r=list(map(int,input('input the second list of the second array: ').split(',')))
B=np.array([t1,r1])
print('Your second array:',B)
C=np.add(A, B)
C

KeyboardInterrupt: Interrupted by user

In [3]:
import numpy as np
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)
A=np.add(x, y)
A


array([[ 6.,  8.],
       [10., 12.]])

In [2]:

import numpy as np
x= np.random.randint(2, 10, size=(2,5))
print(x)
y = x- x.mean(axis=1, keepdims=True)
print(y)

[[7 5 7 8 8]
 [8 6 9 3 2]]
[[ 0.  -2.   0.   1.   1. ]
 [ 2.4  0.4  3.4 -2.6 -3.6]]
